events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name medmaster.app.br;

        # Rota para o Certbot validar o Let's Encrypt
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redireciona todo o tráfego HTTP para HTTPS
        location / {
            return 301 https://$host$request_uri;
        }
    }

    # Bloco HTTPS (Descomente APÓS gerar o certificado pela primeira vez)
    server {
        listen 443 ssl;
        server_name medmaster.app.br;
        
        ssl_certificate /etc/letsencrypt/live/medmaster.app.br/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/medmaster.app.br/privkey.pem;
        
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
        location /api/ {
            proxy_pass http://backend:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
